apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice-deploy  
  namespace : microservice
labels:
    app: configservice-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configservice-deploy
  template:
    metadata:
      labels:
        app: configigservice-deploy
    spec:
      containers:
      - name: configservice-container
        image: nguyenmanhdung/config-service:$CI_COMMIT_SHORT_SHA0.2.0
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: configservice-service
  namespace : microservice
spec:
  type: NodePort
  selector:
    app: configservice-deploy
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30000 