apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice-deploy  
  namespace : ci-test
labels:
    app: configservice-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configservice-deploy
  template:
    metadata:
      labels:
        app: configservice-deploy
    spec:
      containers:
      - name: configservice-container
        image: nguyenmanhdung/config-service:9a79cdeb
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: configservice-service
  namespace : ci-test
spec:
  type: NodePort
  selector:
    app: configservice-deploy
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 31111 